name: CI Workflow

env:
  CONFIG_REPO_NAME: argocd-app-config

on:
  push:
    branches:
      - 'master'
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install pip setuptools wheel
          pip install -r requirements.txt
      - name: Code Testing
        run: |
          python manage.py test
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - name: Format code with black
        uses: psf/black@22.3.0
  docker-build-push:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: hieupham0607/todo-app:${{github.sha}}
  update-manifests:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "updating kubernetes manifest"
          git config --global user.email ci-bot@argocd.com && git config --global user.name ci-bot
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/$CONFIG_REPO_NAME.git
          cd $CONFIG_REPO_NAME
          echo "checkout main branch"
          git checkout main
          echo "updating image tag in values file"
          sed -i "s,tag:.*,tag:\ ${{ github.sha }}," helm/webapp/values.yaml
          git add . && git commit -m "update image tag"
          git push
